rules:
  - id: no-public-fields
    patterns:
      - pattern: public $X $FIELD;
    message: "Avoid using public fields in classes. Consider using private fields with getters and setters."
    severity: ERROR
    languages:
      - java
    path:
      - src/main/java/

  - id: no-hardcoded-credentials
    patterns:
      - pattern: |
          String $VAR = "$SECRET";
      - metavariable-pattern:
          metavariable: $SECRET
          pattern: "hardcoded_password|hardcoded_key"
    message: "Avoid hardcoded credentials in your code."
    severity: ERROR
    languages:
      - java
    path:
      - src/main/java/

  - id: no-open-endpoint
    patterns:
      - pattern: |
          @RequestMapping(value = $URL, method = RequestMethod.GET)
      - pattern-either:
          - pattern: |
              @PreAuthorize("$EXPRESSION")
          - pattern-not: |
              @PreAuthorize
    message: "Endpoints should be secured with appropriate authorization checks."
    severity: WARNING
    languages:
      - java
    path:
      - src/main/java/

  - id: avoid-sql-injection
    patterns:
      - pattern: $QUERY = "SELECT $FIELDS FROM $TABLE WHERE $CONDITION = '" + $VALUE + "'";
    message: "Potential SQL Injection. Use prepared statements or parameterized queries instead."
    severity: ERROR
    languages:
      - java
    path:
      - src/main/java/

  - id: no-log-sensitive-data
    patterns:
      - pattern: logger.info("$SENSITIVE_DATA");
      - pattern: logger.debug("$SENSITIVE_DATA");
    message: "Avoid logging sensitive data."
    severity: WARNING
    languages:
      - java
    path:
      - src/main/java/